myshop/urls.py
from django.urls import re_path, path
from django.contrib.auth import views as auth_views
from . import user_views, views
from django.conf import settings
from django.conf.urls.static import static

# app_name="myshop"
urlpatterns = [
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^brand/(?P<category_name>[\w]+)$', views.brands, name = 'brands'),
    re_path(r'^product/(?P<product_id>[\d]+)$', views.view_product, name='view_product'),
    re_path(r'^add/(?P<product_id>[\d]+)$', views.add_product_to_cart, name='add_product_to_cart'),
    re_path(r'^show-cart$', views.show_cart, name='show_cart'),
    # re_path(r'^change/(?P<action>[a-z]+)/(?P<action>[0-9]+)$', views.add_product_to_cart, name='add_product_to_cart'),
    path("change/<str:action>/<int:product_id>", views.change_product_quantity, name='change_product_quantity'),
    re_path(r'^delete/(?P<product_id>[\d]+)$', views.delete_product_in_cart, name='delete_product_in_cart'),
    re_path(r'^checkout$', views.checkout, name='checkout'),


    re_path(r"^user/register$", user_views.register_user, name='register_user'),
    re_path(r"^user/login$", user_views.login_user, name='login_user'),
    re_path('user/logout/', views.user_logout, name='logout_user'),
    re_path(r"^user/validate$", user_views.validate_username, name='validate_username'),
    # re_path(r"^user/change$", user_views.change_password, name='change_password'),
    # re_path(r"^user/validate$", user_views.validate_username, name='validate_username'),
    re_path('account/', views.account_info, name='account_info'),


    path('account_info/', views.account_info, name='account_info'),
    path('orders/', views.order_list, name='order_list'),

    path('forgot-password/', views.forgot_password, name='forgot_password'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from myshop import user_views

urlpatterns = [
    path("", include("myshop.urls")),
    path("admin/", admin.site.urls),
    path("custom_admin/", include("custom_admin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", default="avatars/default.png")

    def __str__(self):
        return f"{self.user.username} Profile"


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    icon = models.TextField(blank=True)
    category_parent = models.ForeignKey(
        "self", blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Category"
        # ordering = ['name']


class Brand(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    country = models.TextField()
    icon = models.TextField(blank=True)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Brand"


class Detail(models.Model):
    name = models.CharField(max_length=100)
    screen = models.CharField("Màn hình", max_length=100, blank=True)
    operating_system = models.CharField("Hệ điều hành", max_length=100, blank=True)
    rear_camera = models.CharField("Camera sau", max_length=100, blank=True)
    front_camera = models.CharField("Camera trước", max_length=100, blank=True)
    chip = models.CharField("Chip", max_length=50, blank=True)
    RAM = models.CharField("RAM", max_length=100, blank=True)
    memory = models.CharField("Bộ nhớ trong", max_length=200, blank=True)
    sim = models.CharField("SIM", max_length=200, blank=True)
    battery = models.CharField("Pin", max_length=50, blank=True)
    adapter = models.CharField("Sạc", max_length=50, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Detail"


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    stock_quantity = models.IntegerField()
    detail = models.ForeignKey(Detail, on_delete=models.CASCADE)
    image = models.TextField()
    status = models.BooleanField(default=True)  # True là còn, False là hết kinh doanh
    tags = models.ManyToManyField(Tag, related_name="products", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Product"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    path = models.TextField()

    def __str__(self):
        return self.product.name

    class Meta:
        db_table = "ProductImage"


class Promotion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    discount = models.IntegerField()
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField()

    def __str__(self):
        return self.product.name

    class Meta:
        db_table = "Promotion"


class Order(models.Model):
    STATUS_CHOICES = (
        (0, "Đang chờ xác nhận"),
        (1, "Đã xác nhận"),
        (2, "Đang giao hàng"),
        (3, "Giao hàng thành công"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateField(default=timezone.now)
    total_amount = models.IntegerField(null=True)
    phone = models.CharField(max_length=10)
    address = models.TextField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        db_table = "Order"


class OrderDetail(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    amount = models.IntegerField()

    class Meta:
        db_table = "OrderDetail"


class Rating(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="ratings"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stars = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])

    class Meta:
        unique_together = ("product", "user")  # mỗi user chỉ đánh giá 1 lần

    def __str__(self):
        return f"{self.user.username} - {self.product.name}: {self.stars} sao"

myshop/views.py
# Đặt ở đầu file
from django.shortcuts import render, redirect
from django.db.models import Avg
from .models import Product, Rating
from .forms import RatingForm
from django.shortcuts import redirect, render
from django.http.response import JsonResponse
from django.db.models import Min, Max
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.timezone import now
from django.contrib.humanize.templatetags.humanize import intcomma
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import Profile


from django.contrib.auth.models import User
from .models import Order, Product
from django.db.models import Sum, Count
from django.db.models import Q
from django.core.paginator import Paginator
from .forms import UserUpdateForm, AvatarUpdateForm


from django.contrib.auth.decorators import login_required

from myshop.models import (
    Category,
    Brand,
    Product,
    Order,
    OrderDetail,
    Promotion,
    Rating,
)
from myshop.templatetags.custom_filter import get_price_sale, get_price

from django.contrib import messages
from accounts.forms import UserUpdateForm
from .forms import UserUpdateForm, AvatarUpdateForm, CustomPasswordChangeForm

# Create your views here.

from django.db.models.functions import TruncMonth
from django.db.models import Sum
import json
from myshop.forms import PasswordResetCustomForm
from django.contrib.auth.hashers import make_password


def forgot_password(request):
    message = ""
    success = ""

    if request.method == "POST":
        username = request.POST.get("username")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        if new_password != confirm_password:
            message = "Mật khẩu xác nhận không khớp."
        else:
            try:
                user = User.objects.get(username=username)
                user.password = make_password(new_password)
                user.save()
                success = "Mật khẩu đã được đặt lại thành công. Vui lòng đăng nhập lại."
            except User.DoesNotExist:
                message = "Tài khoản không tồn tại."

    return render(
        request, "user/forgot_password.html", {"message": message, "success": success}
    )


# @login_required
# def edit_account(request):
#     if request.method == "POST":
#         user_form = UserUpdateForm(request.POST, instance=request.user)
#         avatar_form = AvatarUpdateForm(
#             request.POST, request.FILES, instance=request.user.profile
#         )

#         if user_form.is_valid() and avatar_form.is_valid():
#             user_form.save()
#             avatar_form.save()
#             messages.success(request, "Thông tin tài khoản đã được cập nhật.")
#             return redirect("account_info")  # Redirect to account info page

#     else:
#         user_form = UserUpdateForm(instance=request.user)
#         avatar_form = AvatarUpdateForm(instance=request.user.profile)

#     context = {
#         "user_form": user_form,
#         "avatar_form": avatar_form,
#     }

#     return render(request, "user/edit_account.html", context)


@login_required
def account_info(request):
    # Tạo Profile nếu chưa có
    if not hasattr(request.user, "profile"):
        Profile.objects.create(user=request.user)

    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        avatar_form = AvatarUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if user_form.is_valid() and avatar_form.is_valid():
            user_form.save()
            avatar_form.save()
            messages.success(request, "Cập nhật thông tin thành công.")
            return redirect("account_info")
    else:
        user_form = UserUpdateForm(instance=request.user)
        avatar_form = AvatarUpdateForm(instance=request.user.profile)

    return render(
        request,
        "user/account_info.html",
        {
            "user_form": user_form,
            "avatar_form": avatar_form,
        },
    )


def index(request):
    categories = Category.objects.filter(category_parent__isnull=True)
    brands = Brand.objects.all()
    query = request.GET.get("q", "")

    products = Product.objects.all().order_by("id")

    if query:
        products = products.filter(
            Q(name__icontains=query) | Q(brand__name__icontains=query)
        )

    product_paginator = Paginator(products, 9)
    page_number = request.GET.get("page")
    page_obj = product_paginator.get_page(page_number)

    products_promotion = Promotion.objects.filter(
        start_date__lte=now(), end_date__gt=now()
    )
    minimum_price = Product.objects.aggregate(Min("price"))["price__min"]
    maximum_price = Product.objects.aggregate(Max("price"))["price__max"]

    context = {
        "categories": categories,
        "brands": brands,
        "query": query,
        "page_obj": page_obj,
        "minimum_price": minimum_price,
        "maximum_price": maximum_price,
        "products_promotion": products_promotion,
    }

    # ❗️Chỉ thêm các phần này nếu không tìm kiếm
    if not query:
        featured_products = Product.objects.all().order_by("id")
        featured_paginator = Paginator(featured_products, 9)
        featured_page_number = request.GET.get("featured_page")
        featured_page = featured_paginator.get_page(featured_page_number)

        best_seller_products = (
            Product.objects.filter(orderdetail__order__status=1)
            .annotate(total_sold=Sum("orderdetail__quantity"))
            .order_by("-total_sold")
            .distinct()
        )
        bestseller_paginator = Paginator(best_seller_products, 6)
        bestseller_page_number = request.GET.get("bestseller_page")
        bestseller_page = bestseller_paginator.get_page(bestseller_page_number)

        context["featured_page"] = featured_page
        context["bestseller_page"] = bestseller_page

    return render(request, "index.html", context)


def brands(request, category_name):  # View list product of a brand

    categories = Category.objects.filter(category_parent__isnull=True)
    brands = Category.objects.get(name=category_name).brand_set.all()
    brand_display = ""
    products = Product.objects.all()
    brand_search = request.GET.get("brand")
    category = Category.objects.get(name=category_name)
    products = Product.objects.filter(category=category)
    if brand_search:
        brand_display = Category.objects.get(name=category_name).brand_set.get(
            name=brand_search
        )
        products = products.filter(brand=brand_display)
    return render(
        request=request,
        template_name="common/brands.html",
        context={
            "brands": brands,
            "products": products,
            "category": category,
            "brand_display": brand_display,
            "categories": categories,
        },
    )


@login_required(login_url="/user/login")
def view_product(request, product_id):
    product_data = ""
    fields = []
    try:
        product_data = Product.objects.get(id=product_id)
        product_detail = product_data.detail
        fields_data = product_detail._meta.get_fields()
        for field in fields_data:
            if field.name in ["product", "id", "name"]:
                continue
            else:
                fields.append(field.name)

        # Thêm phần đánh giá sao
        user_rating = None
        if request.user.is_authenticated:
            user_rating = Rating.objects.filter(
                product=product_data, user=request.user
            ).first()

            if request.method == "POST":
                form = RatingForm(
                    request.POST,
                    instance=user_rating
                    or Rating(product=product_data, user=request.user),
                )
                if form.is_valid():
                    form.save()
                    return redirect("view_product", product_id=product_id)
            else:
                form = RatingForm(instance=user_rating or None)
        else:
            form = None

        tags = product_data.tags.all()
        ratings = product_data.ratings.all()
        avg_rating = ratings.aggregate(Avg("stars"))["stars__avg"]
        info = f"Cấu hình chi tiết của {product_data}"

        return render(
            request=request,
            template_name="product/product-details.html",
            context={
                "info": info,
                "product_data": product_data,
                "fields": fields,
                "product_detail": product_detail,
                "form": form,
                "avg_rating": avg_rating,
                "ratings": ratings,
                "tags": tags,
            },
        )
    except Product.DoesNotExist:
        return render(
            request=request,
            template_name="404.html",
        )


@login_required(login_url="/user/login")
def add_product_to_cart(request, product_id):  # Add a produc to user's cart
    try:
        # Xác định người dùng đăng nhập
        logged_user = request.user
        product_data = Product.objects.get(id=product_id)
        # Kiểm tra xem người dùng có giỏ hàng nào chưa thành công (Status = 0)
        user_has_ordered = Order.objects.get(
            user=logged_user, status=0
        )  # Status = 0 là chưa thành công
        # Người dùng có 1 order chưa thành công.
        # Chia ra làm 2 trường hợp.

        # Người dùng thêm trùng với sản phẩm đã có trong giỏ hàng. Cập nhật dòng Orderdetail với sản phẩm đó và tăng quantity lên 1.
        order = user_has_ordered  # Đổi tên lại cho dễ xử lý
        orderdetail = OrderDetail.objects.get(order=order, product=product_data)

myshop/templates/product/product-details.html
{% extends 'base/__base.html' %}

{% block title %}
	Product Detail
{% endblock title %}

{% load static %}
{% load humanize %}
{% load custom_filter %}

{% block content %}
<style>
	.view-product img {
		border: 1px solid #F7F7F0;
		height: auto;
		width: 70%;
	  }

	.product-img-responsive img {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 60%;

	}

	#similar-product .carousel-inner .item{
		padding-left:100px;
	}
    
	.rating-form {
  margin-top: 20px;
  padding: 20px;
  border-radius: 12px;
  background-color: #f9f9f9;
  box-shadow: 0 4px 10px rgba(0,0,0,0.1);
}

.rating-form h3 {
  margin-bottom: 10px;
  font-size: 1.2rem;
  color: #333;
}

.star-rating select {
  font-size: 18px;
  padding: 8px;
  border-radius: 6px;
  border: 1px solid #ccc;
}

.rating-form button {
  margin-top: 10px;
  padding: 8px 16px;
  border: none;
  border-radius: 8px;
  background-color: #007bff;
  color: white;
  cursor: pointer;
}

.rating-form button:hover {
  background-color: #0056b3;
}

.avg-rating {
  margin-top: 20px;
  font-weight: bold;
  font-size: 2.1rem;
  color: #f39c12;
}

.user-reviews {
  margin-top: 15px;
}

.user-reviews h4 {
  margin-bottom: 8px;
}

.user-reviews p {
  background: #f4f4f4;
  padding: 8px;
  border-radius: 6px;
  margin-bottom: 6px;
}

.product-tags {
  margin-top: 10px;
}

.product-tags .tag {
  display: inline-block;
  background-color: #f1f1f1;
  color: #333;
  padding: 4px 8px;
  margin-right: 6px;
  border-radius: 6px;
  font-size: 13px;
}


</style>

<!--Breadcrumb-->
<div class="container">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item active" aria-current="page">
				<a href="{% url 'index' %}">
					<i class="bi bi-house-door"></i>
					Trang chủ
				</a>
			</li>
			<li class="breadcrumb-item active" aria-current="page">
				<a href="{% url 'brands' category_name=product_data.category.name %}">
					{{product_data.category.description}}
				</a>
			</li>
			<li class="breadcrumb-item" aria-current="page">
				<a href="">
					{{product_data.brand}}
				</a>
			</li>
		</ol>
	</nav>
</div>
<!--Breadcrumb-->

<section>
	<div class="container">
		<div class="row">			
			<div class="col-sm-12 padding-right">
				<div class="product-details"><!--product-details-->
					<div class="col-sm-6">
						<div class="view-product">
							{% if product_data.image|first in 'image' %}
								<img class="thumb" src="{% static product_data.image %}" alt="{{product_data.name}}" />								
							{% else %}
								<img class="thumb" src="{{product_data.image}}" alt="{{product_data.name}}" />												
							{% endif %}
							
						</div>

						{% if product_data.productimage_set.all %}
						<div id="similar-product" class="carousel slide" data-ride="carousel">		
							<!-- Wrapper for slides -->
							<ol class="carousel-indicators">
								{% for product_image in product_data.productimage_set.all %}
								<li data-target="#slider-carousel" data-slide-to="{{forloop.counter0}}" {%if forloop.counter0 == 0 %}class="active"{% endif %}></li>
								{% endfor %}
							</ol>
							
							<div class="carousel-inner">
								{% for product_image in product_data.productimage_set.all %}
									<div class="item{%if forloop.counter0 == 0 %} active{% endif %} product-img-responsive">
										{% if product_image.path|first in 'product_images' %}
											<img src="{% static product_image.path %}" class="product-img-responsive" alt=""/>		
										{% else %}	
											<img src="{{ product_image.path }}" class="product-img-responsive" alt=""/>
										{% endif %}
									</div>
								{% endfor %}
							</div>

							<!-- Controls -->
							<a class="left item-control" href="#similar-product" data-slide="prev">
							  <i class="fa fa-angle-left"></i>
							</a>
							<a class="right item-control" href="#similar-product" data-slide="next">
							  <i class="fa fa-angle-right"></i>
							</a>
						</div>
						{% endif %}
					</div>


					<div class="col-sm-6">
						<div class="product-information"><!--/product-information-->
							<img src="{% static 'images/product-details/new.jpg' %}" class="newarrival" alt="" />
							<h2>{{ product_data.name }}</h2>
							<p>Mã sản phẩm: 1089772{{ product_data.id}}</p>
							<!-- <img src="{% static 'images/product-details/rating.png' %}" alt="" /> -->
							{% if avg_rating %}
							<div class="avg-rating">
							  ⭐ Đánh giá trung bình: {{ avg_rating|floatformat:1 }}/5
							</div>
						  {% endif %}
                            

							<br>
							<span>
								<span>
									{% if product_data.id|check_product_sale %}
										<a style="text-decoration:line-through; color:blueviolet; font-size: 50%; ">{{product_data.price|intcomma}} VND</a>
										<br>
										<a>{{product_data.id|get_price_sale|intcomma}} VND</a>
									{% else %}
										<a>{{product_data.price|intcomma}} VND</a>
									{% endif %}
								</span>
								<br>
								<!--Add to cart-->
								<form action="" method="POST">
									{% csrf_token %}
									<label>Số lượng:</label>
									<!-- <input type="text" value="1" name="product_quantity"/> -->
									<input type="number" id="product_quantity" name="product_quantity" value="1" min="1" max="{{ product_data.stock_quantity }}" required>
									<a data-href="{% url 'add_product_to_cart' product_id=product_data.id %}" class="btn btn-fefault cart" data-logged-user="{{ user.is_authenticated }}">
										<i class="fa fa-shopping-cart"></i> Thêm giỏ hàng
									</a>
								</form>
								<!--Add to cart-->
							</span>
							<!-- <p><b>có sẵn:</b> {% if product_data.stock_quantity > 0 %}Trong kho{%else%}Out Stock{% endif %}</p> -->
							<p><b>Có sẵn:</b>
								{% if product_data.stock_quantity > 0 %}
									Trong kho (Còn lại: {{ product_data.stock_quantity }})
								{% else %}
									Hết hàng
								{% endif %}
							</p>
							
							<p><b>Tình trạng:</b> Mới</p>
							<p><b>Cửa hàng:</b> MOBILE-STORE</p>
							<a href=""><img src="{% static 'images/product-details/share.png' %}" class="share img-responsive"  alt="" /></a>
						</div><!--/product-information-->
					</div>
				</div><!--/product-details-->
			</div>

	
				<div class="category-tab shop-details-tab"><!--category-tab-->
					<div class="col-sm-12">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#details" data-toggle="tab">Chi tiết</a></li>
							<!-- <li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
							<li><a href="#tag" data-toggle="tab">Tag</a></li> -->
							<li><a href="#reviews" data-toggle="tab">Đánh giá </a></li>
						</ul>
					</div>
					<div class="tab-content">
						<div class="tab-pane fade active in"  id="details" >
							<div class="col-sm-12">
								<table class="table table-striped">
									<thead>
									  <tr>
										<th colspan="2">{{info}}</th>
									  </tr>
									</thead>
									
									<tbody>
										{% for field in fields %}
											<tr>
												<td>{{product_detail|getlabel:field}}</td>
												<td>{{product_detail|getattribute:field}}</td>
											</tr>
										{% endfor %}
									</tbody>
								  </table>
							</div>

						</div>
						
						<div class="tab-pane fade" id="reviews" >
							{% if user.is_authenticated %}
							<div class="rating-form">
							  <h3>Đánh giá sản phẩm</h3>
							  <form method="POST">
								{% csrf_token %}
								<div class="star-rating">
								  {{ form.stars }}
								</div>
								<button type="submit">Gửi đánh giá</button>
							  </form>
							</div>
						  {% else %}
							<p><a href="{% url 'login_user' %}">Đăng nhập</a> để đánh giá sản phẩm.</p>
						  {% endif %}
						  
						  {% if avg_rating %}
							<div class="avg-rating">
							  ⭐ Đánh giá trung bình: {{ avg_rating|floatformat:1 }}/5
							</div>
						  {% endif %}
						  
						  {% if ratings %}
							<div class="user-reviews">
							  <h4>Đánh giá từ người dùng</h4>
							  {% for r in ratings %}
								<p><strong>{{ r.user.username }}</strong>: 
								  {{ r.stars }}⭐ - {{ r.comment }}
								</p>
							  {% endfor %}
							</div>
						  {% endif %}
						  
						</div>

						
					</div>
				</div><!--/category-tab-->

				

				<div id="alert-add-product">
					<h1  style="font-size: 300%; margin: auto; text-align: center" >
						<span class="glyphicon glyphicon-ok-sign"></span>
					</h1>
					<h1 id="content" style="text-align: center;">
						{{product_data.id|message_alert}}
					</h1>
				</div>
				
			</div>
		</div>
	</div>


</section>

<script>
	$(document).ready(function() {
		$(".cart").each(function() {
			$(this).click(function() {
				let url = $(this).data('href');
				if ($(this).data('logged-user') === "True") {
					$.ajax({
						type: "GET",
						url: url,
						success: function(data) {
							$("sup.badge").text(data.quantity);
							$("#alert-add-product").show();
							setTimeout(function() {
								$("#alert-add-product").hide();
							}, 1000);
						},
						error: function(xhr, textStatus, errorThrow) {
							console.log(errorThrow);
						}
					})
				}
				else {
					window.location.href = url;
				}
			});
		});
	});
</script>

{% endblock content %}

myshop/templates/product/product-item.html
{% load static %}
{% load humanize %}
{% load custom_filter %}
<div class="col-sm-4">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center" style="min-height: 430px">
                <a href="{% url 'view_product' product_id=product.id %}">
                    {% if product.image|first in 'image' %}
                        <img class="thumb" src="{% static product.image %}" alt="{{product.name}}" />								
                    {% else %}
                        <img class="thumb" src="{{product.image}}" alt="{{product.name}}" />												
                    {% endif %}
                </a>
                {% if product.id|check_product_sale %}
                    <h6 style="position:absolute; bottom:130px; left:17%; text-decoration:line-through; color:blueviolet;">{{product.price|intcomma}} VND</h6>
                    <h2 style="text-align: center;">{{product.id|get_price_sale|intcomma}} VND</h2>
                {% else %}
                    <h2 style="text-align: center;">{{product.price|intcomma}} VND</h2>
                {% endif %}
                <p>{{product.name}}</p>
                <!-- <p>Thương hiệu: {{product.brand.name}}</p> -->
                <a data-href="{% if user.is_authenticated %} {% url 'add_product_to_cart' product_id=product.id %} {% else %} {% url 'login_user' %} {% endif %}"
                    class="btn btn-default add-to-cart"
                    data-logged-user="{{ user.is_authenticated }}">
                    <i class="fa fa-shopping-cart"></i>Thêm giỏ hàng
                </a>
            </div>

            {% if product.id|check_product_sale %} <!--promotion-->
                <!-- <img src="{% static 'images/home/sale.png' %}" class="new" alt="website template image"> -->
                <span class="new" style="background-color: orange; color: white; height:20px; margin:auto;">Giảm {{product.id|get_product_discount}} %</span>
            {% endif %} <!--promotion-->
        </div>
    </div>
</div>